# Generated by Django 4.1 on 2022-08-13 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name_plural": "People"},
        ),
    ]
